spring:
 datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:tcp://localhost/~/testdb
   username: manager
   password: '{cipher}AQAGxjl9FL8y4Tap5QmttzeXcBsFBTZ2j62cH7BYH4I3ZK0mTHMEcMRtT+v7W48DKCNsp+JmF0dIBS3ZqjzEqCgNiTIiK+vt8CkNLRuJxsJRXd8mOpT12fWVzaw6DnmUOqXSWqgh2EPozSSEi7u0kc3iqrf5glgUSYjyNA8GPgWwHU3bYw3MiSgxKv15VRzAHEc8+A41r20fslqoQgDT61Fl7OhNhr3aObiXlEuLlYXQdE9lH+K2MZuURrIOHwRbU7Uzb222/rRpyENnVwHvsws0FqpmI1Vcs5U9DgyeC3pLK5BNbYQBIJ/y8mEKLUNsQYqwaqHRa1cONIiu9uDTs9Ct2d61jpbKvE3ibGq1nSy6MfYauGAnkTlQjwEGWzalxLo='

token:
  expiration_time: 864000000
  secret: '{cipher}AQB3KKJRO3gTwZe/s87e7iJsp3beKfhXj15OFyNMsGBqLYgG1hoxbjyi4g5DxIkT9pHbzS9PSWjEPcINhctQ+n8Q2GnshKkzYUnT8ff+YAkgqq4C6JmE71T5NFGFGaMfOPkmnn7UrEnHHDMxjf0i9iMTSBAh1D9MV/oq8+SbAbA+QHhaRkTARPV7M/hVQAnq/hJVwYoS3K2j4u1T06TQYvS6euVebcvBzdaUZ07zVQeW6jxe5PLCDu7g48MIV11WiXcspjPkQRu7vdIprDSkZt055zTOp9Sfni5Dn9Q8c8GIwviEkmsxM4oFAwMqaA2gFn+I9vqL9CmfVv/mYmjlLitTl9M0iNoUQyQmLfipdLBWDz/fqBHofno9cOObukp1+yqc9GhhcZNaTbXK5cvgCjM2TdqiPVW8PViQtuEzA8o2bQ=='

gateway:
  ip: 192.160.0.18

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    order_is_empty: User's orders is empty.